name: Discord_Link
version: @version@
main: net.dirtcraft.discord.discordlink.DiscordLink
api-version: 1.16
load: STARTUP
authors: [ShinyAfro,Combi]
description: Discord Integration
depend: [Vault]
softdepend: [Essentials]

commands:
  verify:
    description: Links your discord account to the current minecraft account.
    usage: /verify <code>
  unverify:
    description: Unlinks any discord accounts to this minecraft account.
    usage: /unverify
  discord:
    description: Invite you to the discord.
    usage: /discord
  prefix:
    description: Prefix Commands
    usage: /prefix <clear|group|toggle|test|set>